config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root 'books#index'

  resources :books
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
	after_validation :full_name

	before_save :set_full_name

	private

		def set_full_name
			first_name_initial = first_name.slice(0)
			self.full_name = first_name_initial + ". " + last_name
		end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_and_belongs_to_many :categories
  validates :title, presence: true
  validates :body, presence: true

 # before_save :update_categories_count
#
  #private

  	#def update_categories_count
  	#	categories.each do |category|
  	#		category.update(books_count: category.books.count)
  	#	end
  	#end
end

app/models/books_category.rb
class BooksCategory < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :books
  validates :title, presence: true
  validates :title, length: { minimum: 1 }
end

app/models/cateory_list.rb
class CateoryList < ApplicationRecord
has_many :books

end

app/models/user.rb
class User < ApplicationRecor		
	validates :name,  presence: true, length: { maximum: 50 }
	  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },format:{ with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  before_save { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    end

  def new
    @book = Book.new
  end

  
    
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_url(@book)
    else
      render :new
    end
  end

  def show
    find_book
  end

  def edit
    find_book
  end

  def update
    find_book

    if @book.update(book_params)
      redirect_to book_url(@book)
    else
      render :edit
    end
  end

  def destroy
    find_book

    if @book.destroy
      flash[:notice] = "Book deleted"
      redirect_to books_url
    else
      flash[:notice] = "Book could not be deleted"
      redirect_to books_url
    end
   end

  private

    def find_book
      @book = Book.find(params[:id])
    end

  

    def book_params
      params.require(:book).permit(:title, :body, :author_id,:category_ids => [])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 def index
    @category = Category.all
    end

  def new
    @category = Category.new
  end

  
    
  def create
    @category = Category.new(categ_params)
    if @category.save
      redirect_to categories_url(@category)
    else
      render :new
    end
  end

  def show
    find_category
  end

  def edit
    find_category
  end

  def update
    find_category

    if @category.update(categ_params)
      redirect_to categories_url(@category)
    else
      render :edit
    end
  end

  def destroy
    find_category

    if @category.destroy
      flash[:notice] = "Category deleted"
      redirect_to categories_url
    else
      flash[:notice] = "Category could not be deleted"
      redirect_to categories_url
    end
   end

  private

    def find_category
      @category = Category.find(params[:id])
    end

  

    def categ_params
      params.require(:category).permit(:title)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<% if @book.errors.present? %>
  <%= @book.errors.full_messages %>
<% end %>

<%= form_for @book do |form| %>
  <table>
    <tr>
      <td>
        <%= form.label :title %>
      </td>
      <td>
        <%= form.text_field :title %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :body %>
      </td>
      <td>
        <%= form.text_area :body %>
      </td>
    </tr>


    <tr>
      <td>
        <%= form.label :author %>
      </td>
      <td>
        <%= form.select :author_id, options_for_select(Author.all.map{ |a|[a.full_name, a.id] })%>
      </td>
    </tr>
<tr>

      <td>
        <%= form.label :categories %>
      </td><table>
<tr>

   <% categs = Category.all %>
    <% categs.each do |categ| %>
      <%= form.label (categ.title || 'Default categ title') %>  
      <%= form.check_box :category_ids, { multiple: true }, categ.id, nil %>
    <% end %>
  <%= link_to 'New category', new_category_url,method: :get %>


</tr>

  </table>
  <%= form.submit %>
  <%= link_to 'Cancel', books_url, method: :get %>
  <br>

<% end %>

app/views/books/create.html.erb
<h1>Category#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<h1>Lista carti</h1>
<%= button_to 'New Book',new_book_url, method: :get %>
<%= button_to 'Categories',categories_url, method: :get %>
<br>
<% @books.each do |book| %>
  <%= book.title %>
  <div class="actions" style="float:right;">
    <%= link_to "Show", book_url(book) %>
     <%= link_to "Edit", edit_book_url(book) %>
    <%= link_to "Remove", book_url(book), method: :delete, data: { confirm: "Are you sure?" }  %>
  </div>
  <hr style="clear:both;">
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
 <% if @book.errors.present? %>
  <%= @book.errors.full_messages %>
<% end %>


<h3><%= @book.title %></h3>
</b>
<p><%= @book.body %></p>

<h2>Categorii</h2>
<% @book.categories.each do |category| %>
	<%= category.title %>
	<br>
<% end %>

<hr>
<b>
<h7> <%= link_to 'Book list', books_url %></h7>
</b>

app/views/categories/_form.html.erb
<h2>New category</h2>

<%= form_for @category do |form| %>
  <table>
    <tr>
      <td>
        <%= form.label :title %>
      </td>
      <td>
        <%= form.text_field :title %>
      </td>
    </tr>
  
  <%= form.submit %>
  <%= button_to 'Cancel', books_url, method: :get %>

<% end %>

app/views/categories/category.html.erb
<h2>New category</h2>

<%= form_for @category do |form| %>
  <table>
    <tr>
      <td>
        <%= form.label :title %>
      </td>
      <td>
        <%= form.text_field :title %>
      </td>
    </tr>
  
  <%= form.submit %>
  <%= button_to 'Cancel', books_url, method: :get %>

<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<% if @category.errors.present? %>
  <%= @category.errors.full_messages %>
<% end %>
<%= form_for @category do |form| %>
  <table>
    <tr>
      <td>
        <%= form.label :Category %>
      </td>
      <td>
        <%= form.text_field :title %>
      </td>
    </tr>
  </table>
  <%= form.submit %>
  <%= link_to 'Cancel', categories_url, method: :get %>

<% end %>

app/views/categories/index.html.erb
<h1>Category list</h1>
<%= button_to 'New Category', new_category_url, method: :get %>
<%= button_to 'Books', books_url, method: :get %>

<br>
<% @category.each do |categ| %>
  <%= categ.title %>
  <div class="actions" style="float:right;">
    <%= link_to "Edit", edit_category_url(categ) %>
    <%= link_to "Remove", category_url(categ), method: :delete, data: { confirm: "Are you sure?" }  %>
  </div>
  <hr style="clear:both;">
<% end %>

app/views/categories/new.html.erb
<h2>New category</h2>
<% if @category.errors.present? %>
  <%= @category.errors.full_messages %>
<% end %>
<%= form_for @category do |form| %>
  <table>
    <tr>
      <td>
        <%= form.label :Category %>
      </td>
      <td>
        <%= form.text_field :title %>
      </td>
    </tr>
  </table>
  <%= form.submit %>
  <%= link_to 'Cancel', books_url, method: :get %>

<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CursuriBiblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>